### ISSUE TITLE
How to install plugin in Mac OS X

### ISSUE THREAD

**Issue by ceedee666** [bpmn-io/bpmn-js-token-simulation-plugin#16]
Hi, 
I tried to install the plugin in the latest OSX version of the Camunda Modeler. I tried two approaches:
- a resources/plugins dictionary at the same level as the Camunda Modeler.app file
- adding the plugin folder to the Ressources folder inside the Camunda Modeler.app.
In both cases the plugin wasn't recognized. 

How can the plugin be installed in OSX?

Christian

**Comment by ceedee666** [comment]
Hi all,
after some more playing around I figured it out myself. In the OS X version of the Camunda Modeler the plugins need to be put in the following directory inside the Camunda Modeler.app.

`Camunda\ Modeler.app/Contents/MacOS/resources/plugins`

Christian

**Comment by hellereye** [comment]
please do not close this issue, the installation path is not declared in README

**Comment by pinussilvestrus** [comment]
The installation paths are described in [the Modeler docs](https://github.com/camunda/camunda-modeler/tree/develop/docs/plugins). I just added a reference to the README, cf. https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/commit/01f8a400b229b4d81aa128043bc24509e2516e26

Thanks!

**Comment by SirArman98** [comment]
Hello everyone. I put the downloaded file from github into Camunda\ Modeler.app/Contents/MacOS/resources/plugins
And it still does not work for me. Could someone please help?

**Comment by sidorenkoda** [comment]
MacOS Venture 13.0.1 (22A400)
Comunda Modeller 5.7.0
node -v = v19.5.0


Plugin in /Applications/Camunda Modeler.app/Contents/MacOS/resources/plugins/camunda-modeler-plugin-resize-tasks-master folder

npm i 
npm run bundle:watch

`

> camunda-modeler-plugin-resize-tasks@0.1.0 bundle:watch
> webpack --watch

/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/snapdragon-util/index.js:279
});
^

SyntaxError: Unexpected token '}'
    at new Script (node:vm:100:7)
    at NativeCompileCache._moduleCompile (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/snapdragon-node/index.js:5:13)
    at Module._compile (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/braces/lib/parsers.js:3:12)
    at Module._compile (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/braces/index.js:16:15)
    at Module._compile (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/dmitry/Downloads/camunda-modeler-plugin-resize-tasks-master/node_modules/micromatch/index.js:8:14)

Node.js v19.5.0`

Please help!

**Comment by stamateandreiv** [comment]
Hello, for me it worked. 

<img width="627" alt="Screenshot 2024-05-23 at 09 18 43" src="https://github.com/camunda/camunda-modeler-token-simulation-plugin/assets/170603082/559b1a65-233e-4fbd-a6d0-2fade08d1c9f">
