### ISSUE TITLE
Incompatibility Issue with Modeler 3.0.1

### ISSUE THREAD

**Issue by McAlm** [bpmn-io/bpmn-js-token-simulation-plugin#17]
After installing 3.0.1. I always get the following exception: 

[diagram_1.bpmn] A DOM element reference is required
    at new (webpack:///node_modules/min-dom/dist/index.esm.js:75:0)
    at classes (webpack:///node_modules/min-dom/dist/index.esm.js:63:0)
    at file:///Users/swiese/Library/Application%20Support/camunda-modeler/plugins/bpmn-js-token-simulation-plugin-0.8.0/client/client.bundle.js:123:7
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/0.0.js:1:214623
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:362:0)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:348:0)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:310:0)
    at ToggleMode../node_modules/bpmn-js-token-simulation/lib/features/toggle-mode/modeler/ToggleMode.js.ToggleMode.toggleMode (webpack:///node_modules/bpmn-js-token-simulation/lib/features/toggle-mode/modeler/ToggleMode.js:63:0) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]

**Comment by pinussilvestrus** [comment]
Seems like you have to update your plugin version. Since `v0.9.0` we support Camunda-Modeler v3xxx

* [Changelog v0.9.0](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/commit/3b1b0e576e9bc81481c8169567664dd15c72d196)

**Comment by McAlm** [comment]
Great! But unfortunately  v0.9.0 is not yet available as release. Can you actually do the release and push it? That's the only way non-techies can use this plugin. Or am I totally blind?

**Comment by nikku** [comment]
The tag was missing and is [now available](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/releases/tag/v0.9.0).
