### ISSUE TITLE
Plugin doesn't support Camunda Modeller 4.7.0

### ISSUE THREAD

**Issue by ceedee666** [bpmn-io/bpmn-js-token-simulation-plugin#27]
The plugin doesn't support the latest version of the Camunda Modeller. When the Token Simulation is toggled in the Modeller 4.7.0 the following error message is logged:

[/Users/christian/Downloads/diagram_1.bpmn] A DOM element reference is required
    at new (webpack:///node_modules/min-dom/dist/index.esm.js:75:0)
    at classes (webpack:///node_modules/min-dom/dist/index.esm.js:63:0)
    at file:///Users/christian/Library/Application%20Support/camunda-modeler/resources/plugins/bpmn-js-token-simulation-plugin-master/client/client.bundle.js:123:7
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/2.2.js:1:49241
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:371:33)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:352:23)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:313:23)
    at ToggleMode../node_modules/bpmn-js-token-simulation/lib/features/toggle-mode/modeler/ToggleMode.js.ToggleMode.toggleMode (webpack:///node_modules/bpmn-js-token-simulation/lib/features/toggle-mode/modeler/ToggleMode.js:63:0)
    at apply (webpack:///node_modules/@sentry/browser/esm/helpers.js:71:22) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]

__Steps to Reproduce__

1. Install Camunda Modeller 4.7.0
2. Toggle the Token Simulation 

__Environment__
- OS: macOs Big Sur (11.2.3)
- Latest version of the plug in

**Comment by nikku** [comment]
Thanks for the bug report. We'll have a look.

**Comment by nikku** [comment]
Fixed with `v0.12.0`.
